// Copyright 2020-2023 Tecdrop (www.tecdrop.com)
// Use of this source code is governed by an MIT-style license that can be
// found in the LICENSE file.

import 'package:color_hap/models/random_color.dart';
import 'package:shared_preferences/shared_preferences.dart';

import '../models/color_type.dart';

// -----------------------------------------------------------------------------------------------
// immersiveMode setting (not persistent)
// -----------------------------------------------------------------------------------------------

bool _immersiveMode = false;

/// Whether the main screens are in immersive mode.
bool get immersiveMode => _immersiveMode;
set immersiveMode(bool value) => _immersiveMode = value;

// -----------------------------------------------------------------------------------------------
// colorType setting
// -----------------------------------------------------------------------------------------------

const String _colorTypeKey = 'colorType';

ColorType _colorType = ColorType.webColor;

/// The last kind of random colors generated by the user.
ColorType get colorType => _colorType;
set colorType(ColorType value) {
  _colorType = value;
  _saveColorType();
}

/// Saves the color type setting to persistent storage.
Future<void> _saveColorType() async {
  SharedPreferences preferences = await SharedPreferences.getInstance();
  await preferences.setInt(_colorTypeKey, _colorType.index);
}

// -----------------------------------------------------------------------------------------------
// favList setting
// -----------------------------------------------------------------------------------------------

const String _favListKey = 'favList';

List<RandomColor> favList = <RandomColor>[];
// List<RandomColor> _favList = <RandomColor>[];

/// The list of favorite colors.
// List<RandomColor> get favList => _favList;
// set favList(List<RandomColor> value) {
//   _favList = value;
//   _saveFavList();
// }

/// Saves the favorite colors list to persistent storage.
// Future<void> _saveFavList() async {
//   SharedPreferences preferences = await SharedPreferences.getInstance();
//   await preferences.setStringList(
//     _favListKey,
//     _favList.map((RandomColor color) => color.title).toList(),
//   );
// }

// -----------------------------------------------------------------------------------------------
// Common
// -----------------------------------------------------------------------------------------------

/// Loads app settings from persistent storage.
Future<void> loadSettings() async {
  SharedPreferences preferences = await SharedPreferences.getInstance();
  _colorType = ColorType.values[preferences.getInt(_colorTypeKey) ?? 0];
}
