// Copyright 2020-2024 Tecdrop (www.tecdrop.com)
// Use of this source code is governed by an MIT-style license that can be
// found in the LICENSE file.
//
// Flutter icons CustomIcons
// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
// This font was generated by FlutterIcon.com, which is derived from Fontello.

/// Custom icons used in the app.
library;

import 'package:flutter/widgets.dart';

const _kFontFam = 'CustomIcons';
const String? _kFontPkg = null;

// ignore: constant_identifier_names
const IconData reorder_off_outlined =
    IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
