// Copyright 2020-2026 Tecdrop SRL. All rights reserved.
// Use of this source code is governed by an MIT-style license that can be found
// in the LICENSE file or at https://www.tecdrop.com/colorhap/license/.

import 'package:shared_preferences/shared_preferences.dart';

import '../models/color_favorites_list.dart';
import '../models/color_type.dart';
import '../models/random_color_generator.dart';

final _asyncPrefs = SharedPreferencesAsync();

// -----------------------------------------------------------------------------------------------
// colorType setting
// -----------------------------------------------------------------------------------------------

const String _colorTypeKey = 'colorType';

/// The last type of random colors generated by the user.
ColorType _colorType = .webColor;
ColorType get colorType => _colorType;
set colorType(ColorType value) {
  _colorType = value;
  _saveColorType();
}

/// Saves the color type setting to persistent storage.
Future<void> _saveColorType() async {
  await _asyncPrefs.setInt(_colorTypeKey, _colorType.index);
}

// -----------------------------------------------------------------------------------------------
// favList setting
// -----------------------------------------------------------------------------------------------

const String _colorFavoritesListKey = 'colorFavoritesList';

/// The list of favorite colors.
ColorFavoritesList colorFavoritesList = ColorFavoritesList(
  onChanged: () => saveColorFavoritesList(),
);

/// Saves the favorite colors list to persistent storage.
///
/// This should be called whenever the list of favorite colors changes (add, remove, clear, etc.)
Future<void> saveColorFavoritesList() async {
  final favKeyList = colorFavoritesList.toKeyList();
  await _asyncPrefs.setStringList(_colorFavoritesListKey, favKeyList);
}

// -----------------------------------------------------------------------------------------------
// Common
// -----------------------------------------------------------------------------------------------

/// Loads app settings from persistent storage.
Future<void> loadSettings(Map<ColorType, RandomColorGenerator> generators) async {
  // Load the last color type used by the user
  _colorType = ColorType.values[await _asyncPrefs.getInt(_colorTypeKey) ?? 0];

  // Load the favorite colors list
  final favKeyList = await _asyncPrefs.getStringList(_colorFavoritesListKey);
  colorFavoritesList.loadFromKeyList(favKeyList, generators: generators);

  // If new format is empty, try migrating from old JSON format
  if (favKeyList == null || favKeyList.isEmpty) {
    // Load the favorites JSON string list from the old SharedPreferences
    final oldPreferences = await SharedPreferences.getInstance();
    final oldJsonList = oldPreferences.getStringList(_colorFavoritesListKey);

    // Only migrate if old data exists
    if (oldJsonList != null && oldJsonList.isNotEmpty) {
      // ignore: deprecated_member_use_from_same_package
      colorFavoritesList.loadFromJsonStringList(oldJsonList);

      // Explicitly save to new format
      await saveColorFavoritesList();

      // Only clear old format after successful save
      await oldPreferences.remove(_colorFavoritesListKey);
    }
  }
}
