// Copyright 2020-2025 Tecdrop SRL. All rights reserved.
// Use of this source code is governed by an MIT-style license that can be found
// in the LICENSE file or at https://www.tecdrop.com/colorhap/license/.

import 'dart:math';

import 'color_item.dart';
import 'color_type.dart';

/// An interface for generating random colors of a specific [ColorType].
abstract interface class RandomColorGenerator {
  /// The type of colors generated by this generator.
  ColorType get colorType;

  /// Generates the next random color.
  ColorItem next(Random random);

  /// The total number of unique random colors that can be generated by this generator.
  int get length;

  /// Returns the index-th color in the generator.
  ColorItem elementAt(int index);
}
