// Copyright 2020-2026 Tecdrop SRL. All rights reserved.
// Use of this source code is governed by an MIT-style license that can be found
// in the LICENSE file or at https://www.tecdrop.com/colorhap/license/.

import 'dart:math';
import 'dart:ui';

import 'package:flutter/foundation.dart' show kDebugMode;

import '../models/color_item.dart';
import '../models/color_type.dart';
import '../models/random_color_generator.dart';

/// A random color generator that mixes the other color generators.
///
/// It randomly selects one of the provided color generators to produce a color, with a weighted
/// probability to balance the frequency of different color types.
class RandomMixedColorGenerator implements RandomColorGenerator {
  RandomMixedColorGenerator(this.generators) {
    // Define the weights for each color type to influence their selection probability (2-4-5-6-3)
    _typeWeights.addAll(List.filled(2, .basicColor)); // 10%
    _typeWeights.addAll(List.filled(4, .webColor)); // 20%
    _typeWeights.addAll(List.filled(5, .namedColor)); // 25%
    _typeWeights.addAll(List.filled(6, .attractiveColor)); // 30%
    _typeWeights.addAll(List.filled(3, .trueColor)); // 15%
  }

  /// The map of color generators to mix.
  final Map<ColorType, RandomColorGenerator> generators;

  /// A list of color types used to weight the selection of generators.
  final List<ColorType> _typeWeights = [];

  @override
  ColorType get colorType => .mixedColor;

  /// Generates a random color by selecting one of the mixed generators at random.
  ///
  /// The selection is weighted to try to balance the frequency of different color types.
  @override
  ColorItem next(Random random) {
    final selectedType = _typeWeights[random.nextInt(_typeWeights.length)];
    return generators[selectedType]!.next(random);
  }

  /// The total number of unique colors that can be generated by mixing the generators.
  ///
  /// No matter how many colors we mix, the total number of possible colors is still the total
  /// number of true colors (0x000000 to 0xFFFFFF).
  @override
  int get length => 0xFFFFFF + 1;

  /// Returns a color item by index by delegating to the True Color generator.
  ///
  /// This method should not be called because the mixed color generator does not have a
  /// well-defined order of colors. It is implemented to satisfy the interface.
  @override
  ColorItem elementAt(int index) {
    if (kDebugMode) {
      print('RandomMixedColorGenerator.elementAt($index) should not be called directly.');
    }

    return generators[ColorType.trueColor]!.elementAt(index);
  }

  /// Returns the [ColorItem] for the given [color] by delegating to the True Color generator.
  ///
  /// This method should not be called. It is implemented to satisfy the interface.
  @override
  ColorItem? elementFrom(Color color) {
    if (kDebugMode) {
      print('RandomMixedColorGenerator.elementFrom($color) should not be called directly.');
    }

    return generators[ColorType.trueColor]!.elementFrom(color);
  }
}
